title: Cyborg
author: Channabasava H
email: channachannu.97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Research and development in network and information security domain.
 Automation tools, scripts for understanding netowrk secuirty concepts written in python.
 Artificial Intelligence in cybersecurity domain.
 
#Theme
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  channachannu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
